# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad95104c2fa5facda3252bdff01648086cdbe80c68696f9a071f8558c54a5e4e9fc270a2795ac6035fc0c060b2803a349c4d6d3b75983b29c00fcb8d7e5d8da7

test:
  secret_key_base: d142dddd3d92091a5c9700163e6004d7b7de3ec04c37b7160081fc248d8b75e550a5e26d28f953bd4492dbb865be39d9ba7040d180271037829ec0bb1cf466b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
